//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./GrammarSpec/Portugol.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PortugolParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPortugolListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] PortugolParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] PortugolParser.ProgramaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloco([NotNull] PortugolParser.BlocoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloco([NotNull] PortugolParser.BlocoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandos([NotNull] PortugolParser.ComandosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandos([NotNull] PortugolParser.ComandosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracaoFuncao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracaoFuncao([NotNull] PortugolParser.DeclaracaoFuncaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracaoFuncao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracaoFuncao([NotNull] PortugolParser.DeclaracaoFuncaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracaoProcedimento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracaoProcedimento([NotNull] PortugolParser.DeclaracaoProcedimentoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracaoProcedimento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracaoProcedimento([NotNull] PortugolParser.DeclaracaoProcedimentoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.listaParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListaParams([NotNull] PortugolParser.ListaParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.listaParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListaParams([NotNull] PortugolParser.ListaParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] PortugolParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] PortugolParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] PortugolParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] PortugolParser.TipoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComando([NotNull] PortugolParser.ComandoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComando([NotNull] PortugolParser.ComandoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracaoVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracaoVar([NotNull] PortugolParser.DeclaracaoVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracaoVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracaoVar([NotNull] PortugolParser.DeclaracaoVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribuicao([NotNull] PortugolParser.AtribuicaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribuicao([NotNull] PortugolParser.AtribuicaoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>chamadaEscreva</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChamadaEscreva([NotNull] PortugolParser.ChamadaEscrevaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>chamadaEscreva</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChamadaEscreva([NotNull] PortugolParser.ChamadaEscrevaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>chamadaGenerica</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChamadaGenerica([NotNull] PortugolParser.ChamadaGenericaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>chamadaGenerica</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChamadaGenerica([NotNull] PortugolParser.ChamadaGenericaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoRetorne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoRetorne([NotNull] PortugolParser.ComandoRetorneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoRetorne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoRetorne([NotNull] PortugolParser.ComandoRetorneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoDoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoDoEnquanto([NotNull] PortugolParser.ComandoDoEnquantoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoDoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoDoEnquanto([NotNull] PortugolParser.ComandoDoEnquantoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoPara([NotNull] PortugolParser.ComandoParaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoPara([NotNull] PortugolParser.ComandoParaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.listaArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListaArgs([NotNull] PortugolParser.ListaArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.listaArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListaArgs([NotNull] PortugolParser.ListaArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] PortugolParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] PortugolParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RelExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelExpr([NotNull] PortugolParser.RelExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RelExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelExpr([NotNull] PortugolParser.RelExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] PortugolParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] PortugolParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.relacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelacao([NotNull] PortugolParser.RelacaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.relacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelacao([NotNull] PortugolParser.RelacaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.soma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoma([NotNull] PortugolParser.SomaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.soma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoma([NotNull] PortugolParser.SomaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermo([NotNull] PortugolParser.TermoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermo([NotNull] PortugolParser.TermoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] PortugolParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] PortugolParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NegExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegExpr([NotNull] PortugolParser.NegExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NegExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegExpr([NotNull] PortugolParser.NegExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PosExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPosExpr([NotNull] PortugolParser.PosExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PosExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPosExpr([NotNull] PortugolParser.PosExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimExpr([NotNull] PortugolParser.PrimExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimExpr([NotNull] PortugolParser.PrimExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.prim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrim([NotNull] PortugolParser.PrimContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.prim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrim([NotNull] PortugolParser.PrimContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.chamadaFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChamadaFunc([NotNull] PortugolParser.ChamadaFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.chamadaFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChamadaFunc([NotNull] PortugolParser.ChamadaFuncContext context);
}
