//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./GrammarSpec/Portugol.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PortugolParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPortugolVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] PortugolParser.ProgramaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.declaracoes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracoes([NotNull] PortugolParser.DeclaracoesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.declaracao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracao([NotNull] PortugolParser.DeclaracaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] PortugolParser.TipoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandos([NotNull] PortugolParser.ComandosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComando([NotNull] PortugolParser.ComandoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtribuicao([NotNull] PortugolParser.AtribuicaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoPara([NotNull] PortugolParser.ComandoParaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoSaida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoSaida([NotNull] PortugolParser.ComandoSaidaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.blocoComandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlocoComandos([NotNull] PortugolParser.BlocoComandosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] PortugolParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.exprLogica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprLogica([NotNull] PortugolParser.ExprLogicaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.exprRelacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprRelacional([NotNull] PortugolParser.ExprRelacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.exprAritmetica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAritmetica([NotNull] PortugolParser.ExprAritmeticaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermo([NotNull] PortugolParser.TermoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subExpr</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubExpr([NotNull] PortugolParser.SubExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>negacao</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegacao([NotNull] PortugolParser.NegacaoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>booleano</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleano([NotNull] PortugolParser.BooleanoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumero([NotNull] PortugolParser.NumeroContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>textoLiteral</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextoLiteral([NotNull] PortugolParser.TextoLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identificador</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentificador([NotNull] PortugolParser.IdentificadorContext context);
}
