//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./GrammarSpec/Portugol.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PortugolParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPortugolVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] PortugolParser.ProgramaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloco([NotNull] PortugolParser.BlocoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandos([NotNull] PortugolParser.ComandosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.declaracaoFuncao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracaoFuncao([NotNull] PortugolParser.DeclaracaoFuncaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.declaracaoProcedimento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracaoProcedimento([NotNull] PortugolParser.DeclaracaoProcedimentoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.listaParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaParams([NotNull] PortugolParser.ListaParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] PortugolParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] PortugolParser.TipoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComando([NotNull] PortugolParser.ComandoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.declaracaoVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracaoVar([NotNull] PortugolParser.DeclaracaoVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtribuicao([NotNull] PortugolParser.AtribuicaoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>chamadaEscreva</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChamadaEscreva([NotNull] PortugolParser.ChamadaEscrevaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>chamadaGenerica</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChamadaGenerica([NotNull] PortugolParser.ChamadaGenericaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoRetorne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoRetorne([NotNull] PortugolParser.ComandoRetorneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoDoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoDoEnquanto([NotNull] PortugolParser.ComandoDoEnquantoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandoPara([NotNull] PortugolParser.ComandoParaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.listaArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaArgs([NotNull] PortugolParser.ListaArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] PortugolParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RelExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelExpr([NotNull] PortugolParser.RelExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] PortugolParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.relacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelacao([NotNull] PortugolParser.RelacaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.soma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoma([NotNull] PortugolParser.SomaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermo([NotNull] PortugolParser.TermoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] PortugolParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegExpr([NotNull] PortugolParser.NegExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PosExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPosExpr([NotNull] PortugolParser.PosExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrimExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimExpr([NotNull] PortugolParser.PrimExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.prim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrim([NotNull] PortugolParser.PrimContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PortugolParser.chamadaFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChamadaFunc([NotNull] PortugolParser.ChamadaFuncContext context);
}
