//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./GrammarSpec/Portugol.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPortugolListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class PortugolBaseListener : IPortugolListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] PortugolParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] PortugolParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracoes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracoes([NotNull] PortugolParser.DeclaracoesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracoes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracoes([NotNull] PortugolParser.DeclaracoesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracao([NotNull] PortugolParser.DeclaracaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracao([NotNull] PortugolParser.DeclaracaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] PortugolParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] PortugolParser.TipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandos([NotNull] PortugolParser.ComandosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandos([NotNull] PortugolParser.ComandosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComando([NotNull] PortugolParser.ComandoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComando([NotNull] PortugolParser.ComandoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtribuicao([NotNull] PortugolParser.AtribuicaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtribuicao([NotNull] PortugolParser.AtribuicaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoPara([NotNull] PortugolParser.ComandoParaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoPara([NotNull] PortugolParser.ComandoParaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoSaida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoSaida([NotNull] PortugolParser.ComandoSaidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoSaida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoSaida([NotNull] PortugolParser.ComandoSaidaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.blocoComandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlocoComandos([NotNull] PortugolParser.BlocoComandosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.blocoComandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlocoComandos([NotNull] PortugolParser.BlocoComandosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] PortugolParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] PortugolParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.exprLogica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprLogica([NotNull] PortugolParser.ExprLogicaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.exprLogica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprLogica([NotNull] PortugolParser.ExprLogicaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.exprRelacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprRelacional([NotNull] PortugolParser.ExprRelacionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.exprRelacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprRelacional([NotNull] PortugolParser.ExprRelacionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.exprAritmetica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAritmetica([NotNull] PortugolParser.ExprAritmeticaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.exprAritmetica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAritmetica([NotNull] PortugolParser.ExprAritmeticaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermo([NotNull] PortugolParser.TermoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermo([NotNull] PortugolParser.TermoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>subExpr</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubExpr([NotNull] PortugolParser.SubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>subExpr</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubExpr([NotNull] PortugolParser.SubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>negacao</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegacao([NotNull] PortugolParser.NegacaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>negacao</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegacao([NotNull] PortugolParser.NegacaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>booleano</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleano([NotNull] PortugolParser.BooleanoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>booleano</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleano([NotNull] PortugolParser.BooleanoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumero([NotNull] PortugolParser.NumeroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumero([NotNull] PortugolParser.NumeroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>textoLiteral</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextoLiteral([NotNull] PortugolParser.TextoLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>textoLiteral</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextoLiteral([NotNull] PortugolParser.TextoLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>identificador</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentificador([NotNull] PortugolParser.IdentificadorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>identificador</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentificador([NotNull] PortugolParser.IdentificadorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
