//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./GrammarSpec/Portugol.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPortugolListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class PortugolBaseListener : IPortugolListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] PortugolParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] PortugolParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloco([NotNull] PortugolParser.BlocoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloco([NotNull] PortugolParser.BlocoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandos([NotNull] PortugolParser.ComandosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandos([NotNull] PortugolParser.ComandosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracaoFuncao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracaoFuncao([NotNull] PortugolParser.DeclaracaoFuncaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracaoFuncao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracaoFuncao([NotNull] PortugolParser.DeclaracaoFuncaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracaoProcedimento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracaoProcedimento([NotNull] PortugolParser.DeclaracaoProcedimentoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracaoProcedimento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracaoProcedimento([NotNull] PortugolParser.DeclaracaoProcedimentoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.listaParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListaParams([NotNull] PortugolParser.ListaParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.listaParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListaParams([NotNull] PortugolParser.ListaParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] PortugolParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] PortugolParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] PortugolParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] PortugolParser.TipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComando([NotNull] PortugolParser.ComandoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComando([NotNull] PortugolParser.ComandoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracaoVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracaoVar([NotNull] PortugolParser.DeclaracaoVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracaoVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracaoVar([NotNull] PortugolParser.DeclaracaoVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtribuicao([NotNull] PortugolParser.AtribuicaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtribuicao([NotNull] PortugolParser.AtribuicaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>chamadaEscreva</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChamadaEscreva([NotNull] PortugolParser.ChamadaEscrevaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>chamadaEscreva</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChamadaEscreva([NotNull] PortugolParser.ChamadaEscrevaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>chamadaGenerica</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChamadaGenerica([NotNull] PortugolParser.ChamadaGenericaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>chamadaGenerica</c>
	/// labeled alternative in <see cref="PortugolParser.chamadaProc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChamadaGenerica([NotNull] PortugolParser.ChamadaGenericaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoRetorne"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoRetorne([NotNull] PortugolParser.ComandoRetorneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoRetorne"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoRetorne([NotNull] PortugolParser.ComandoRetorneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoDoEnquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoDoEnquanto([NotNull] PortugolParser.ComandoDoEnquantoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoDoEnquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoDoEnquanto([NotNull] PortugolParser.ComandoDoEnquantoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandoPara([NotNull] PortugolParser.ComandoParaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandoPara([NotNull] PortugolParser.ComandoParaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.listaArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListaArgs([NotNull] PortugolParser.ListaArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.listaArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListaArgs([NotNull] PortugolParser.ListaArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] PortugolParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] PortugolParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RelExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelExpr([NotNull] PortugolParser.RelExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RelExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelExpr([NotNull] PortugolParser.RelExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] PortugolParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="PortugolParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] PortugolParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.relacao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelacao([NotNull] PortugolParser.RelacaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.relacao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelacao([NotNull] PortugolParser.RelacaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.soma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoma([NotNull] PortugolParser.SomaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.soma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoma([NotNull] PortugolParser.SomaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermo([NotNull] PortugolParser.TermoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermo([NotNull] PortugolParser.TermoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpr([NotNull] PortugolParser.NotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpr([NotNull] PortugolParser.NotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NegExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegExpr([NotNull] PortugolParser.NegExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NegExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegExpr([NotNull] PortugolParser.NegExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PosExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosExpr([NotNull] PortugolParser.PosExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PosExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosExpr([NotNull] PortugolParser.PosExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimExpr([NotNull] PortugolParser.PrimExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimExpr</c>
	/// labeled alternative in <see cref="PortugolParser.un"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimExpr([NotNull] PortugolParser.PrimExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.prim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrim([NotNull] PortugolParser.PrimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.prim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrim([NotNull] PortugolParser.PrimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.chamadaFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChamadaFunc([NotNull] PortugolParser.ChamadaFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.chamadaFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChamadaFunc([NotNull] PortugolParser.ChamadaFuncContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
