//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./GrammarSpec/Portugol.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PortugolParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPortugolListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] PortugolParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] PortugolParser.ProgramaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.blocoPrincipal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlocoPrincipal([NotNull] PortugolParser.BlocoPrincipalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracoes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracoes([NotNull] PortugolParser.DeclaracoesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracoes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracoes([NotNull] PortugolParser.DeclaracoesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.declaracao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracao([NotNull] PortugolParser.DeclaracaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.declaracao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracao([NotNull] PortugolParser.DeclaracaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] PortugolParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] PortugolParser.TipoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandos([NotNull] PortugolParser.ComandosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandos([NotNull] PortugolParser.ComandosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComando([NotNull] PortugolParser.ComandoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComando([NotNull] PortugolParser.ComandoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribuicao([NotNull] PortugolParser.AtribuicaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribuicao([NotNull] PortugolParser.AtribuicaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoCondicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoCondicional([NotNull] PortugolParser.ComandoCondicionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoEnquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoEnquanto([NotNull] PortugolParser.ComandoEnquantoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoPara([NotNull] PortugolParser.ComandoParaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoPara"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoPara([NotNull] PortugolParser.ComandoParaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.comandoSaida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandoSaida([NotNull] PortugolParser.ComandoSaidaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.comandoSaida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandoSaida([NotNull] PortugolParser.ComandoSaidaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.blocoComandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlocoComandos([NotNull] PortugolParser.BlocoComandosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.blocoComandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlocoComandos([NotNull] PortugolParser.BlocoComandosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] PortugolParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] PortugolParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.exprLogica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLogica([NotNull] PortugolParser.ExprLogicaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.exprLogica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLogica([NotNull] PortugolParser.ExprLogicaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.exprRelacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprRelacional([NotNull] PortugolParser.ExprRelacionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.exprRelacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprRelacional([NotNull] PortugolParser.ExprRelacionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.exprAritmetica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprAritmetica([NotNull] PortugolParser.ExprAritmeticaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.exprAritmetica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprAritmetica([NotNull] PortugolParser.ExprAritmeticaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermo([NotNull] PortugolParser.TermoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PortugolParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermo([NotNull] PortugolParser.TermoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>subExpr</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubExpr([NotNull] PortugolParser.SubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>subExpr</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubExpr([NotNull] PortugolParser.SubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>negacao</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegacao([NotNull] PortugolParser.NegacaoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>negacao</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegacao([NotNull] PortugolParser.NegacaoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>booleano</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleano([NotNull] PortugolParser.BooleanoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>booleano</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleano([NotNull] PortugolParser.BooleanoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumero([NotNull] PortugolParser.NumeroContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumero([NotNull] PortugolParser.NumeroContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>textoLiteral</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextoLiteral([NotNull] PortugolParser.TextoLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>textoLiteral</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextoLiteral([NotNull] PortugolParser.TextoLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identificador</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentificador([NotNull] PortugolParser.IdentificadorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identificador</c>
	/// labeled alternative in <see cref="PortugolParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentificador([NotNull] PortugolParser.IdentificadorContext context);
}
